<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-MU-DT-J34669" name="com.travelex.automation.api.wnp.OriginAPI" tests="2" failures="1" timestamp="24 Nov 2016 07:34:05 GMT" time="141.032" errors="0">
  <testcase name="originApiTest1" time="0.000" classname="com.travelex.automation.api.wnp.OriginAPI">
    <failure type="org.testng.TestNGException" message="
Method public void com.travelex.automation.api.wnp.OriginAPI.originApiTest1(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : ApiDataProvider in class com.travelex.automation.api.common.DataReader">
      <![CDATA[org.testng.TestNGException: 
Method public void com.travelex.automation.api.wnp.OriginAPI.originApiTest1(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : ApiDataProvider in class com.travelex.automation.api.common.DataReader
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:269)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1335)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1051)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1140)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- originApiTest1 -->
  <testcase name="originApiTest" time="141.032" classname="com.travelex.automation.api.wnp.OriginAPI"/>
</testsuite> <!-- com.travelex.automation.api.wnp.OriginAPI -->
